// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjncfoNF8G7XtgQLuvEqRfydAGaLtrzWw',
    appId: '1:402801541323:web:2583e54aec3948c79d1b4e',
    messagingSenderId: '402801541323',
    projectId: 'tiktok2-willis-abc',
    authDomain: 'tiktok2-willis-abc.firebaseapp.com',
    storageBucket: 'tiktok2-willis-abc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5eIUM7nMisWYUUbsBlaZEzC3BRS3mV_w',
    appId: '1:402801541323:android:1b68d3923f1bca619d1b4e',
    messagingSenderId: '402801541323',
    projectId: 'tiktok2-willis-abc',
    storageBucket: 'tiktok2-willis-abc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4T3vsynos6SxV-XyfdDlW0eS_JqO9coo',
    appId: '1:402801541323:ios:8daf23d03a83b3979d1b4e',
    messagingSenderId: '402801541323',
    projectId: 'tiktok2-willis-abc',
    storageBucket: 'tiktok2-willis-abc.firebasestorage.app',
    iosBundleId: 'com.example.tiktok2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjncfoNF8G7XtgQLuvEqRfydAGaLtrzWw',
    appId: '1:402801541323:web:a4b7a99317f923919d1b4e',
    messagingSenderId: '402801541323',
    projectId: 'tiktok2-willis-abc',
    authDomain: 'tiktok2-willis-abc.firebaseapp.com',
    storageBucket: 'tiktok2-willis-abc.firebasestorage.app',
  );

}